name: swiftui_table_demo
options:
  bundleIdPrefix: com.freewind
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  swiftui_table_demo:
    type: application
    platform: macOS
    productName: swiftui_table_demo
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.freewind.swiftuitabledemo
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: NO
    scheme:
      testTargets: []
schemes:
  swiftui_table_demo:
    build:
      targets:
        swiftui_table_demo: all
    run:
      config: Debug
